name: CICD

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
            repository: Exabyte-io/actions
            token: ${{ secrets.BOT_GITHUB_TOKEN }}
            path: actions

      - name: Run tests
        uses: ./actions/js/test
        with:
          node-version: ${{ matrix.node-version }}


  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}

  run-py-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8.6]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v3
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Run python unit tests
        uses: ./actions/py/test
        with:
          python-version: ${{ matrix.python-version }}
          unit-test-directory: tests/py/unit
          bot-ssh-key: ${{ secrets.BOT_GITHUB_KEY }}
