name: CICD

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  run-py-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.9.x
          - 3.10.x
          - 3.11.x
          # Uncomment after fixing
          # AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
          # - 3.12.x

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Run python tests
        uses: ./actions/py/test
        with:
          python-version: ${{ matrix.python-version }}

  run-js-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Run JS validate
        uses: ./actions/js/validate
        with:
          node-version: '20.x'

      - name: Run JS tests
        uses: ./actions/js/test
        with:
          node-version: ${{ matrix.node-version }}

  publish-js-package:
    needs: [run-js-tests]
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish JS release
        uses: ./actions/js/publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}


  publish-py-package:
    needs: [run-py-tests]
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v4
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions

      - name: Publish python release
        uses: ./actions/py/publish
        with:
          python-version: 3.x
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
          # Tag is created by the publish action for JS package
          publish-tag: 'false'
