name: CICD

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: Exabyte-io/actions/js/test@main
        with:
          node-version: ${{ matrix.node-version }}


  publish:
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v2
      - uses: Exabyte-io/actions/js/publish@main
        with:
          node-version: 12.21.x
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
