name: Branch

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Exabyte-io/actions/js/test@main
      - uses: Exabyte-io/actions/js/publish@main
